### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/docker#1]
Updates to the Linuxbrew Docker images will be posted here in this issue.

**Comment by sjackman** [comment]
The Docker image `linuxbrew/linuxbrew` is running on Ubuntu 16.04 LTS (Xenial Xerus).
The Docker image `linuxbrew/alpine` is running on Alpine Linux 3.6.
The Docker image `linuxbrew/debian` is running on Debian 9 (Stretch).
See https://github.com/Linuxbrew/docker#readme

Dockerfile are available for CentOS and other versions of Ubuntu. Open an issue if you would like a prebuilt Docker image for any of these or other distributions of Linux.

**Comment by slhck** [comment]
Is this repository still maintained or recommended for running Linuxbrew in Docker?

It would be great to have a Dockerfile for Ubuntu bionic given that this is the latest LTS.

Simply doing `s/xenial/bionic` in the Dockerfile works.

That said, I see this when running Linuxbrew:

```
==> Migrating from Linuxbrew/brew to Homebrew/brew
  Linuxbrew/brew has been merged into Homebrew/brew!
  Linuxbrew/brew will no longer be updated.
  Your git remote has been changed from
     https://github.com/Linuxbrew/brew.git
  to https://github.com/Homebrew/brew
```

Should the remote URLs be changed in all the Dockerfiles as well?

**Comment by maxim-belkin** [comment]
> Is this repository still maintained

Yes

> recommended for running Linuxbrew in Docker?

This is one way of using Linuxbrew.

> Should the remote URLs be changed in all the Dockerfiles as well?

Yes.

**Comment by sjackman** [comment]
The recommended way of running Linuxbrew in Docker is with the Docker image `linuxbrew/brew`.
See https://hub.docker.com/r/linuxbrew/brew

**Comment by sjackman** [comment]
Note that `linuxbrew/brew` has been renamed to `homebrew/brew` https://hub.docker.com/r/homebrew/brew
