### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/docker#13]
IMO, it should

* Build all the changed images (we can start by having it simply build *ALL* of them)
* Lint them with https://www.npmjs.com/package/dockerfilelint

**Comment by sjackman** [comment]
We can use Docker Hub automated builds to built the images automatically whenever this GitHub repo changes.

**Comment by bw-yuhogg** [comment]
> We can use Docker Hub automated builds to built the images automatically whenever this GitHub repo changes.

Definitely, that's what I'm planning to do on #11 

I still personally want to use a linter of some sort on them though. (I'm open to suggestions if you know a better one)

**Comment by sjackman** [comment]
I'm afraid that I've never used a linter for Docker. Good idea though.

**Comment by bw-yuhogg** [comment]
Closed in #15
