### ISSUE TITLE
TRAVIS issue

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/docker#31]
```
script:
  - find . -name Dockerfile | xargs dockerfilelint
  - for dockerDir in *; do make $dockerDir; done
```

The for loop will match the files like README.md and Makefile?
Maybe `find .  -maxdepth 1 -mindepth 1 -type d -exec make {} \;`

**Comment by sjackman** [comment]
Thanks, Torsten. I've opened PR #33 to resolve this issue.
