### ISSUE TITLE
Can't build image for CentOS 5

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/docker#48]
Currently, it fails with
```
M2Crypto.SSL.SSLError: tlsv1 alert protocol version
```
My suggestion: have necessary files right in the repo and use Docker `COPY` command instead of trying to download them with `urlgrabber`

**Comment by sjackman** [comment]
Mike wasn't able to get CentOS 5 to work either. I suggest that we discontinue support for it.
`portable-ruby` is built using Debian 7 (Wheezy).
See https://github.com/Homebrew/homebrew-portable-ruby/blob/ff91f44bf891c35209825f0df627e40afccf3437/docker/Dockerfile.x86_64#L4

**Comment by sjackman** [comment]
Alternatively, we could find HTTP mirrors for all the necessary files to boot strap `openssl` and `curl`.

**Comment by sjackman** [comment]
Do Bintray and/or GitHub releases support HTTP?

**Comment by maxim-belkin** [comment]
Forgot to close this one.
Updated documentation is available at https://github.com/Linuxbrew/brew/wiki/CentOS-5
