### ISSUE TITLE
stop using USER linuxbrew?

### ISSUE THREAD

**Issue by AlJohri** [Linuxbrew/docker#68]
as the recommended image is `linuxbrew/brew` as per: https://github.com/Linuxbrew/docker/issues/1#issuecomment-483090421

it would be great if the `USER` situation was consistent throughout all `linuxbrew` images

I tried using a dockerfile written using `linuxbrew/brew` and switching to `linuxbrew/debian` and found that I needed to change my paths due to the non-root USER. had to change paths from from `/app` to `~/app`

I would prefer if the `root` user was used since that is more common in the docker and then bring back this PR: https://github.com/Linuxbrew/docker/pull/42 and revert this PR: https://github.com/Linuxbrew/docker/pull/57

**Comment by AlJohri** [comment]
here's a sample error I'm getting due to the `linuxbrew` USER. it's all in the `~/app` folder yet still these issues sporadically appear:

<img width="2560" alt="Screen Shot 2020-01-07 at 3 09 05 PM" src="https://user-images.githubusercontent.com/2790092/71925737-b960bb80-315f-11ea-8cc5-4ea0b33d081a.png">

**Comment by AlJohri** [comment]
Changing the start of my Dockerfile to:

```
FROM linuxbrew/debian
USER root
```

fixes my issues. still think this should be the default (and at least consistent across linuxbrew docker images) perhaps by adding `USER root` at the end of the existing Dockerfiles

**Comment by sjackman** [comment]
> It used to be that Homebrew would refuse to run as `root`. It still does outside of Docker, but it now allows running as `root` within a Docker container. So, these Dockefiles could all be updated to match https://github.com/Homebrew/brew/blob/master/Dockerfile where it creates the `linuxbrew` user but doesn't `USER linuxbrew`.

https://github.com/Linuxbrew/docker/pull/42#issuecomment-571739627
