### ISSUE TITLE
Fix broken centos8 Dockerfile

### ISSUE THREAD

**Issue by VonUniGE** [Linuxbrew/docker#69]
When building the centos8 image with:
```
cd centos8
docker build -t linuxbrew-centos8 .
```
We obtain:
```
[error] character map file `UTF-8' not found: No such file or directory
[error] default character map file `ANSI_X3.4-1968' not found: No such file or directory
```
The solution is to install the packages `glibc-locale-source glibc-langpack-en` as explained in this Stackoverflow answer : [How to fix 'character map file `UTF-8' not found'](https://stackoverflow.com/questions/58304278/how-to-fix-character-map-file-utf-8-not-found)

Then we obtain another error:
```
==> Downloading and installing Homebrew...
Failed during: git init -q
```
The solution is to installl the git package.

I will provide a commit for this.

**Comment by sjackman** [comment]
Fixed by PR #70
